apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: kh-car-checker
spec:
  runInterval: 60s # The interval that Kuberhealthy will run your check on
  timeout: 2m # After this much time, Kuberhealthy will kill your check and consider it "failed"
  podSpec: # The exact pod spec that will run.  All normal pod spec is valid here.
    containers:
    - image: jdowni000/car-checker:v1.1.1 # The image of the check you just pushed
      imagePullPolicy: Always # During check development, it helps to set this to 'Always' to prevent on-node image caching.
      name: main
      env:
        - name: "TARGET_URL"
          value: "http://a39b2df774eb311eabbe902ee0ba4f44-2011198479.us-west-2.elb.amazonaws.com/?car=Roadster" # The URL that applicaiton will use to look for a specified string
        - name: "TARGET_STRING"
          value: "driving mile 0" # The string that will be used to parse through provided URL
