apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: kh-test-check
  namespace: kuberhealthy
spec:
  runInterval: 30s
  podSpec:
    containers:
      - env:
          - name: SOME_ENV_VAR
            value: "12345"
        image: testexternalcheck:latest
        imagePullPolicy: IfNotPresent
        name: main
        resources:
          requests:
            cpu: 10m
            memory: 50Mi