apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: ssl-selfsign-expiry
  namespace: kuberhealthy
spec:
  runInterval: 24h
  timeout: 15m
  podSpec:
    containers:
      - env:
          # Domain name env variable must be updated to the domain on which you wish to check the SSL for
          - name: DOMAIN_NAME
            value: "kubernetes.default"
          # If not using default SSL port of 443, port name env variable must be updated  
          - name: PORT
            value: "443"
          # Number of days until certificate expiration to test for  
          - name: DAYS
            value: "60"
          # If "true", the TLS handshake will be skipped. This is only intended to check certificate expiration, not validity/security  
          - name: INSECURE
            value: "true"
        image: kuberhealthy/ssl-expiry-check:v1.2.0
        imagePullPolicy: IfNotPresent
        name: main
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
