// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "khStateClient/khcheckClient/typed/khstate/v1"

	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeComcastV1 struct {
	*testing.Fake
}

func (c *FakeComcastV1) KuberhealthyStates(namespace string) v1.KuberhealthyStateInterface {
	return &FakeKuberhealthyStates{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeComcastV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
