apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: pod-status-check
  namespace: kube-system
spec:
  runInterval: 2m
  timeout: 1m
  podSpec:
    containers:
      - env:
          - name: TARGET_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        image: quay.io/comcast/pod-status-check:1.0.0
        imagePullPolicy: Always
        name: main
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
