apiVersion: v1
kind: Service
metadata:
  labels:
    app: kuberhealthy
    component: kuberhealthy
  annotations:
    #service.beta.kubernetes.io/aws-load-balancer-internal: "0.0.0.0/0"
    #external-dns.alpha.kubernetes.io/hostname: "kuberhealthy.yourdomain.com."
    {{- if .Values.prometheus.enableScraping -}}
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.service.externalPort }}
    prometheus.io/path: "/metrics"
    {{- end -}}
  name: kuberhealthy
  namespace: kuberhealthy
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    name: http
    targetPort: 8080
  selector:
    app: kuberhealthy
