apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: kh-test-fail-short-timeout
  namespace: kuberhealthy
spec:
  extraAnnotations:
    comcast.com/testAnnotation: test.annotation
  extraLabels:
    testLabel: testLabel
  podSpec:
    containers:
      - env:
          - name: REPORT_FAILURE
            value: "false"
          - name: REPORT_DELAY
            value: "5s"
        image: kuberhealthy/test-check:v1.4.1
        imagePullPolicy: Always
        name: main
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
  runInterval: 30s
  timeout: 1s
---
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: kh-test-default
  namespace: default
spec:
  extraAnnotations:
    comcast.com/testAnnotation: test.annotation
  extraLabels:
    testLabel: testLabel
  podSpec:
    containers:
      - env:
          - name: REPORT_FAILURE
            value: "false"
          - name: REPORT_DELAY
            value: "5s"
        image: kuberhealthy/test-check:v1.4.0
        imagePullPolicy: Always
        name: main
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
  runInterval: 30s
  timeout: 2m
---
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: kh-test-kube-system
  namespace: kube-system
spec:
  extraAnnotations:
    comcast.com/testAnnotation: test.annotation
  extraLabels:
    testLabel: testLabel
  podSpec:
    containers:
      - env:
          - name: REPORT_DELAY
            value: "5s"
          - name: REPORT_FAILURE
            value: "false"
        image: kuberhealthy/test-check:v1.4.0
        imagePullPolicy: Always
        name: main
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
  runInterval: 30s
  timeout: 2m
---
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: kh-daemonset-check
  namespace: kuberhealthy
spec:
  extraAnnotations: null
  extraLabels: null
  podSpec:
    containers:
      - env:
          - name: POD_NAMESPACE
            value: kuberhealthy
        image: docker-proto.repo.theplatform.com/kh-check-daemonset:1.0.0
        imagePullPolicy: Always
        name: main
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
  runInterval: 30s
  timeout: 15m
---
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: kh-test-fail-bad-image
  namespace: kuberhealthy
spec:
  extraAnnotations:
    comcast.com/testAnnotation: test.annotation
  extraLabels:
    testLabel: testLabel
  podSpec:
    containers:
      image: integrii/kh-test-check:doesnotexist
      imagePullPolicy: Always
      name: main
      resources:
        requests:
          cpu: 10m
          memory: 50Mi
  runInterval: 30s
  timeout: 2m
---
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: kh-test-fail-too-big
  namespace: kuberhealthy
spec:
  extraAnnotations:
    comcast.com/testAnnotation: test.annotation
  extraLabels:
    testLabel: testLabel
  podSpec:
    image: kuberhealthy/test-check:v1.4.0
    imagePullPolicy: Always
    name: main
    resources:
      requests:
        cpu: "800"
        memory: 50Mi
  runInterval: 30s
  timeout: 2m
---
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: kh-test-failure
  namespace: kuberhealthy
spec:
  extraAnnotations:
    comcast.com/testAnnotation: test.annotation
  extraLabels:
    testLabel: testLabel
  podSpec:
    containers:
      - env:
          - name: REPORT_DELAY
            value: "5s"
          - name: REPORT_FAILURE
            value: "true"
        image: kuberhealthy/test-check:v1.4.0
        imagePullPolicy: Always
        name: main
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
  runInterval: 30s
  timeout: 2m
---
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: kh-test-pass
  namespace: kuberhealthy
spec:
  extraAnnotations:
    comcast.com/testAnnotation: test.annotation
  extraLabels:
    testLabel: testLabel
  podSpec:
    containers:
      - env:
          - name: REPORT_DELAY
            value: "5s"
          - name: REPORT_FAILURE
            value: "false"
        image: kuberhealthy/test-check:v1.4.0
        imagePullPolicy: Always
        name: main
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
  runInterval: 30s
  timeout: 2m
---
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: kiam-tester-canary
  namespace: kuberhealthy
spec:
  extraAnnotations:
    iam.amazonaws.com/role: arn:aws:iam::303027209135:role/OneCloud/kiam-lambda-list-test
  extraLabels:
    kuberhealthy-check: kiam-tester-canary
  podSpec:
    containers:
      - image: docker-proto.repo.theplatform.com/kiam-tester:unstable
        imagePullPolicy: Always
        name: kiam-tester-canary
        resources:
          requests:
            cpu: 15m
            memory: 50Mi
  runInterval: 30s
  timeout: 2m30s
