---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kuberhealthy-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kuberhealthy-manager
subjects:
  - kind: ServiceAccount
    name: kuberhealthy
    namespace: kuberhealthy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuberhealthy-manager
rules:
- apiGroups:
  - kuberhealthy.github.io
  resources:
  - kuberhealthychecks
  - kuberhealthychecks/finalizers
  - kuberhealthychecks/status
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
