apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuberhealthy
  namespace: kuberhealthy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuberhealthy
  template:
    metadata:
      labels:
        app: kuberhealthy
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: /metrics
    spec:
      serviceAccountName: kuberhealthy
      containers:
      - name: kuberhealthy
        image: docker.io/kuberhealthy/kuberhealthy:localdev
        imagePullPolicy: Never
        env:
        - name: KH_LISTEN_ADDRESS
          value: ":80"
        - name: KH_LOG_LEVEL
          value: "info"
        - name: KH_MAX_JOB_AGE
          value: ""
        - name: KH_MAX_CHECK_POD_AGE
          value: ""
        - name: KH_MAX_COMPLETED_POD_COUNT
          value: "0"
        - name: KH_MAX_ERROR_POD_COUNT
          value: "5"
        - name: KH_ERROR_POD_RETENTION_DAYS
          value: "4"
        - name: KH_PROM_SUPPRESS_ERROR_LABEL
          value: "false"
        - name: KH_PROM_ERROR_LABEL_MAX_LENGTH
          value: "0"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KH_SERVICE_NAME
          value: "kuberhealthy"
        - name: KH_DEFAULT_RUN_INTERVAL
          value: "10m"
        - name: KH_TERMINATION_GRACE_PERIOD
          value: "5m"
        - name: KH_DEFAULT_CHECK_TIMEOUT
          value: "30s"
        - name: KH_DEFAULT_NAMESPACE
          value: "kuberhealthy"
        - name: KH_TLS_CERT_FILE
          value: "/tls/tls.crt"
        - name: KH_TLS_KEY_FILE
          value: "/tls/tls.key"
        ports:
        - containerPort: 80
        - containerPort: 8080
        volumeMounts:
        - name: webhook-tls
          mountPath: /tls
          readOnly: true
      volumes:
      - name: webhook-tls
        secret:
          secretName: kuberhealthy-webhook-tls
          optional: true
