apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuberhealthy
  namespace: kuberhealthy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuberhealthy
  template:
    metadata:
      labels:
        app: kuberhealthy
    spec:
      containers:
      - name: kuberhealthy
        image: docker.io/kuberhealthy/kuberhealthy:localdev
        imagePullPolicy: Never
        env:
        - name: TARGET_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KH_CHECK_REPORT_HOSTNAME
          value: "kuberhealthy.kuberhealthy.svc.cluster.local"
        ports:
        - containerPort: 8080
