# Enables admission of legacy comcast.github.io/v1 KuberhealthyCheck resources
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: khchecks.comcast.github.io
spec:
  group: comcast.github.io
  scope: Namespaced
  names:
    plural: khchecks
    singular: khcheck
    kind: KuberhealthyCheck
    shortNames:
      - khc
      - khcheck
      - kuberhealthycheck
  versions:
    - name: v1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: OK
          jsonPath: .status.ok
          type: boolean
        - name: RunInterval
          jsonPath: .spec.runInterval
          type: string
        - name: ErrorMessage
          jsonPath: .status.errors[0]
          type: string
        - name: Timeout
          jsonPath: .spec.timeout
          type: string
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                runInterval:
                  type: string
                timeout:
                  type: string
                extraAnnotations:
                  type: object
                  additionalProperties:
                    type: string
                extraLabels:
                  type: object
                  additionalProperties:
                    type: string
                podSpec:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                podAnnotations:
                  type: object
                  additionalProperties:
                    type: string
                podLabels:
                  type: object
                  additionalProperties:
                    type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                ok:
                  type: boolean
                errors:
                  type: array
                  items:
                    type: string
                runDuration:
                  type: integer
                  format: int64
                lastRunUnix:
                  type: integer
                  format: int64
                namespace:
                  type: string
                additionalMetadata:
                  type: string
                currentUUID:
                  type: string
      subresources:
        status: {}
