apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: kuberhealthy-legacy-conversion
webhooks:
  - name: legacy.kuberhealthy.conversion
    admissionReviewVersions:
      - v1
    sideEffects: None
    failurePolicy: Ignore
    clientConfig:
      service:
        name: kuberhealthy
        namespace: kuberhealthy
        path: /api/convert
        port: 8080
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lVQXdib244a24wVHJCZUFNUnA4NFk2ZnJPd0Zzd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0h6RWRNQnNHQTFVRUF3d1VhM1ZpWlhKb1pXRnNkR2g1TFhkbFltaHZiMnN3SUJjTk1qVXdPVEF5TURZeQpOekUxV2hnUE1qRXlOVEE0TURrd05qSTNNVFZhTUI4eEhUQWJCZ05WQkFNTUZHdDFZbVZ5YUdWaGJIUm9lUzEzClpXSm9iMjlyTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFwd0JUMjVGUU5haloKU2g3MzUzZCt4UlQ1RDRKOHphby9yZG5JeU8zRHk3dExVOGlPNTRaMVY4STJ4TWJKTDdxSngvVWV5UktLemtsTwpya0Z0UVlEZ0Q1TitOM3VrU2ZtTnlEVHVZUTM4ZTFWMy9HN1VvMUViT0Y4Tm90c0xXc0JxbmR6TWZmME9PWU5uCjZ0cVhLQ3phd09LVFk0eHZoMHRWK3k1WDNFY0YzU25DTWR5QzdxSlpCaHkvNUU3SFJMNERIYzFRRkJCSGh1aWoKK3lDQlBMQWRlVEN6ZHUxelRpcFpzcS9wd2lSdVZvT3l5RVAxazJPVnZIUGhlOENiSnpTOWtzaFprbWl0aUp0VwozZkRWTW9jZjZpOTl2VlVwcHNPZ2ZtT0xpY0M3TWI3eUdRaWhVWCtWazhuZmVVZGtUazhnRHhvTFNtN1Rwd0FRCm1kTFkyZjBMaVFJREFRQUJvMU13VVRBZEJnTlZIUTRFRmdRVU9XdnNwUGpiZUVVZXN5Rm1jK0Q0bktSV2RGVXcKSHdZRFZSMGpCQmd3Rm9BVU9XdnNwUGpiZUVVZXN5Rm1jK0Q0bktSV2RGVXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBRE1ZMnBIQmt5UkxDV3FrMkNYMVJBRkJrOWxURXRLREdaYUIrClZhRHJxaEo1NGRyQkNxdW9zUVZLWHhTQW53eDdJb3cxQnJZTkhicjk4cldWWVYyS2JpaXpkTnpUeXBMVU9KRlAKVDZOTUk2dnJmK2J3YkVjbE53S0FscHp5aHFQSmZPWjBsMzRLZSs5TmdwNENaTDVObGRHQXU4VUdrN2hxOTFBWQp5a01sODZCb0Myd3hyWUZqQXIzQjJKWjhtY1lJdGsrQURWUVVSTHJxMm11WUF3QWorcHA1ZGJXb0VteGJlR0NNClJLWGhxZlVrRi9Pa2N3ejVvVGZVb01KZ1dCUDJONGtvU0NXWGthTUZwVHVyY0tBcks2UzdYRkNPcHQwWmthbHUKZWZCUHd0YkJUcHN5dG5zVzJxaGdRVG90TDJWZFhLcFhSbngrVnBYSklnSDFLdEtwUmc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations:
          - CREATE
        apiGroups:
          - comcast.github.io
        apiVersions:
          - v1
        resources:
          - kuberhealthychecks
