FROM golang:1.24.1 AS builder
LABEL LOCATION="git@github.com:kuberhealthy/kuberhealthy.git"
LABEL DESCRIPTION="Kuberhealthy - The Kubernetes operator for synthetic checks."
ARG GIT_REV

# Build a /app dir with the files we need in it
COPY . /src
RUN mkdir /app
RUN cp /src/openapi.yaml /app/openapi.yaml
RUN mkdir -p /app/assets \
    && cp -r /src/assets/. /app/assets/

# Build the container
WORKDIR /src/cmd/kuberhealthy
RUN go version
ENV CGO_ENABLED=0
RUN go test -v -short ./...
RUN go build -v -ldflags "-X main.GitRevision=${GIT_REV}" -o /app/kuberhealthy

FROM scratch
WORKDIR /app
COPY --from=builder /app /app
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /etc/passwd /etc/passwd
ENTRYPOINT ["/app/kuberhealthy"]
