FROM golang:1.24.1 AS builder
LABEL LOCATION="git@github.com:kuberhealthy/kuberhealthy.git"
LABEL DESCRIPTION="Kuberhealthy - The Kubernetes operator for synthetic checks."
COPY . /src
WORKDIR /src/cmd/kuberhealthy
RUN go version
ENV CGO_ENABLED=0
RUN mkdir /app
RUN cp /src/openapi.yaml /app/openapi.yaml
RUN mkdir /app/assets
RUN cp /src/assets/logo-square.png /app/assets/logo-square.png
RUN go test -v -short ./...
RUN go build -v -o /app/kuberhealthy

FROM scratch
WORKDIR /app
COPY --from=builder /app /app
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /etc/passwd /etc/passwd
ENTRYPOINT ["/app/kuberhealthy"]
