---
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: resource-quota
  namespace: kuberhealthy
spec:
  runInterval: 30m
  timeout: 5m
  podSpec:
    containers:
      - name: resource-quota
        image: kuberhealthy/resource-quota-check:v1.3.1
        imagePullPolicy: IfNotPresent
        env:
          - name: BLACKLIST
            value: "default"
          - name: WHITELIST
            value: "kube-system,kuberhealthy"
        resources:
          requests:
            cpu: 15m
            memory: 15Mi
          limits:
            cpu: 50m
    restartPolicy: Never
    terminationGracePeriodSeconds: 30
    serviceAccountName: kuberhealthy-resource-quota
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: ClusterRoleBinding
metadata:
  name: kuberhealthy-resource-quota
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kuberhealthy-resource-quota
subjects:
  - kind: ServiceAccount
    name: kuberhealthy-resource-quota
    namespace: kuberhealthy
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: ClusterRole
metadata:
  name: kuberhealthy-resource-quota
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - resourcequotas
    verbs:
      - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kuberhealthy-resource-quota
  namespace: kuberhealthy
