---
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: resource-quota
  namespace: kuberhealthy
spec:
  runInterval: 10m
  timeout: &resource_quota_check_timeout 1m
  podSpec:
    containers:
    - name: resource-quota
      image: quay.io/comcast/resource-quota-check:0.0.2
      imagePullPolicy: Always
      env:
        - name: DEBUG
          value: "true"
        - name: CHECK_TIME_LIMIT
          value: *resource_quota_check_timeout
      resources:
        requests:
          cpu: 25m
          memory: 15Mi
        limits:
          cpu: 50m
      restartPolicy: Never
    terminationGracePeriodSeconds: 30
