---
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: resource-quota
  namespace: kuberhealthy
spec:
  runInterval: 3m
  timeout: &resource_quota_check_timeout 1m
  podSpec:
    containers:
    - name: resource-quota
      image: quay.io/comcast/resource-quota-check:1.0.0
      imagePullPolicy: Always
      env:
        - name: BLACKLIST
          value: "true"
        - name: BLACKLIST_NAMESPACES
          value: "default,istio-system"
        - name: CHECK_TIME_LIMIT
          value: *resource_quota_check_timeout
      resources:
        requests:
          cpu: 15m
          memory: 15Mi
        limits:
          cpu: 50m
      restartPolicy: Never
    terminationGracePeriodSeconds: 30
