apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/namespace.yaml
  - base/deployment.yaml
  - base/service.yaml
  - base/healthcheckCrd.yaml
  - base/legacyKhcheckCrd.yaml
  - base/clusterrole.yaml
  - base/serviceaccount.yaml
  - base/mutatingwebhook.yaml
  - base/webhook-tls-secret.yaml
