apiVersion: comcast.github.io/v1
kind: KuberhealthyJob
metadata:
  name: daemonset-job
  namespace: kuberhealthy
spec:
  # Make sure this Kuberhealthy check timeout is GREATER THAN the daemonset checker timeout
  # set in the env var CHECK_POD_TIMEOUT. Default is set to 5m (5 minutes).
  timeout: 12m
  podSpec:
    containers:
      - env:
          - name: POD_NAMESPACE
            value: "kuberhealthy"
          - name: ALLOWED_TAINTS
            value: "node.kubernetes.io/unschedulable:NoSchedule"
        image: kuberhealthy/daemonset-check:v3.2.4-test
        imagePullPolicy: Always
        name: main
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
    serviceAccountName: daemonset-khcheck
---
#apiVersion: comcast.github.io/v1
#kind: KuberhealthyJob
#metadata:
#  name: deployment
#  namespace: kuberhealthy
#spec:
#  timeout: 15m
#  podSpec:
#    containers:
#      - name: deployment
#        image: kuberhealthy/deployment-check:v1.6.2
#        imagePullPolicy: IfNotPresent
#        env:
#          - name: CHECK_DEPLOYMENT_REPLICAS
#            value: "4"
#          - name: CHECK_DEPLOYMENT_ROLLING_UPDATE
#            value: "true"
#        resources:
#          requests:
#            cpu: 25m
#            memory: 15Mi
#          limits:
#            cpu: 40m
#        restartPolicy: Never
#    serviceAccountName: deployment-sa
#    terminationGracePeriodSeconds: 60
#---
#apiVersion: comcast.github.io/v1
#kind: KuberhealthyJob
#metadata:
#  name: dns-status-internal
#  namespace: kuberhealthy
#spec:
#  timeout: 15m
#  podSpec:
#    containers:
#      - env:
#          - name: HOSTNAME
#            value: "kubernetes.default"
#          - name: NODE_NAME
#            valueFrom:
#              fieldRef:
#                fieldPath: spec.nodeName
#        image: kuberhealthy/dns-resolution-check:v1.4.0
#        imagePullPolicy: IfNotPresent
#        name: main
#        resources:
#          requests:
#            cpu: 10m
#            memory: 50Mi
