apiVersion: v1
kind: Namespace
metadata:
  name: aws
---
apiVersion: stacks.crossplane.io/v1alpha1
kind: ClusterStackInstall
metadata:
  name: provider-aws
  namespace: aws
spec:
  package: "crossplane/provider-aws:v0.7.1"
