# Derived from https://github.com/kuberhealthy/daemonset-check/blob/main/healthcheck.yaml
# Update the image tag to a release version as needed.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: daemonset-khcheck
  namespace: kuberhealthy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: daemonset-khcheck
  namespace: kuberhealthy
rules:
  - apiGroups: ["", "apps"]
    resources: ["daemonsets", "pods"]
    verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: daemonset-khcheck
  namespace: kuberhealthy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: daemonset-khcheck
subjects:
  - kind: ServiceAccount
    name: daemonset-khcheck
    namespace: kuberhealthy
---
apiVersion: kuberhealthy.github.io/v2
kind: HealthCheck
metadata:
  name: daemonset
  namespace: kuberhealthy
spec:
  runInterval: 15m
  timeout: 12m
  podSpec:
    spec:
      serviceAccountName: daemonset-khcheck
      containers:
        - name: daemonset-check
          image: kuberhealthy/daemonset-check:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_NAMESPACE
              value: "kuberhealthy"
      restartPolicy: Never
