[package]
name = "kuberhealthy-example"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "=0.11.22", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
