// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	scheme "khJobClient/khcheckClient/scheme"
	"time"

	v1 "github.com/kuberhealthy/kuberhealthy/v2/pkg/apis/khjob/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KuberhealthyJobsGetter has a method to return a KuberhealthyJobInterface.
// A group's client should implement this interface.
type KuberhealthyJobsGetter interface {
	KuberhealthyJobs(namespace string) KuberhealthyJobInterface
}

// KuberhealthyJobInterface has methods to work with KuberhealthyJob resources.
type KuberhealthyJobInterface interface {
	Create(ctx context.Context, kuberhealthyJob *v1.KuberhealthyJob, opts metav1.CreateOptions) (*v1.KuberhealthyJob, error)
	Update(ctx context.Context, kuberhealthyJob *v1.KuberhealthyJob, opts metav1.UpdateOptions) (*v1.KuberhealthyJob, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.KuberhealthyJob, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.KuberhealthyJobList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.KuberhealthyJob, err error)
	KuberhealthyJobExpansion
}

// kuberhealthyJobs implements KuberhealthyJobInterface
type kuberhealthyJobs struct {
	client rest.Interface
	ns     string
}

// newKuberhealthyJobs returns a KuberhealthyJobs
func newKuberhealthyJobs(c *ComcastV1Client, namespace string) *kuberhealthyJobs {
	return &kuberhealthyJobs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the kuberhealthyJob, and returns the corresponding kuberhealthyJob object, and an error if there is any.
func (c *kuberhealthyJobs) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.KuberhealthyJob, err error) {
	result = &v1.KuberhealthyJob{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kuberhealthyjobs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KuberhealthyJobs that match those selectors.
func (c *kuberhealthyJobs) List(ctx context.Context, opts metav1.ListOptions) (result *v1.KuberhealthyJobList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.KuberhealthyJobList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kuberhealthyjobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kuberhealthyJobs.
func (c *kuberhealthyJobs) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("kuberhealthyjobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a kuberhealthyJob and creates it.  Returns the server's representation of the kuberhealthyJob, and an error, if there is any.
func (c *kuberhealthyJobs) Create(ctx context.Context, kuberhealthyJob *v1.KuberhealthyJob, opts metav1.CreateOptions) (result *v1.KuberhealthyJob, err error) {
	result = &v1.KuberhealthyJob{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("kuberhealthyjobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kuberhealthyJob).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a kuberhealthyJob and updates it. Returns the server's representation of the kuberhealthyJob, and an error, if there is any.
func (c *kuberhealthyJobs) Update(ctx context.Context, kuberhealthyJob *v1.KuberhealthyJob, opts metav1.UpdateOptions) (result *v1.KuberhealthyJob, err error) {
	result = &v1.KuberhealthyJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kuberhealthyjobs").
		Name(kuberhealthyJob.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(kuberhealthyJob).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the kuberhealthyJob and deletes it. Returns an error if one occurs.
func (c *kuberhealthyJobs) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kuberhealthyjobs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kuberhealthyJobs) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kuberhealthyjobs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched kuberhealthyJob.
func (c *kuberhealthyJobs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.KuberhealthyJob, err error) {
	result = &v1.KuberhealthyJob{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("kuberhealthyjobs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
