apiVersion: v1
kind: Pod
metadata:
  name: bad-pod-restarter # Create a bad pod that continuously restarts to verify the check works
  namespace: kube-system
spec:
  containers:
    - name: bad-pod-restart
      image: ubuntu
      imagePullPolicy: IfNotPresent
      command: ["/bin/bash", "-ec", "sleep 5", "exit 0"]
  restartPolicy: Always
