apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: kh-kiam-check
  namespace: kuberhealthy
spec:
  extraAnnotations:
    iam.amazonaws.com/role: <role-arn>
  runInterval: 1m
  timeout: 45s
  podSpec:
    containers:
    - name: kh-kiam-check
      image: quay.io/comcast/kiam-check:1.0.0
      imagePullPolicy: IfNotPresent
      env:
      - name: AWS_REGION
        value: us-west-2
      resources:
        requests:
          cpu: 15m
          memory: 10Mi
        limits:
          cpu: 30m
      restartPolicy: Always

          