apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: kiam
  namespace: kuberhealthy
spec:
  extraAnnotations:
    iam.amazonaws.com/role: <role-arn> # Replace this value with your ARN
  runInterval: 5m
  timeout: 15m
  podSpec:
    containers:
      - name: kiam
        image: kuberhealthy/kiam-check:v1.3.1
        imagePullPolicy: IfNotPresent
        env:
          - name: AWS_REGION
            value: us-west-2
        resources:
          requests:
            cpu: 15m
            memory: 10Mi
          limits:
            cpu: 30m
        restartPolicy: Always
