apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: kuberhealthy-metadata-unreachable
  namespace: kuberhealthy
spec:
  runInterval: 30m
  timeout: 125s
  podSpec:
    containers:
      - env:
          - name: CHECK_POD_TIMEOUT
            value: "10s"
          - name: CONNECTION_TARGET
            value: "tcp://169.254.169.254:80"
          - name: CONNECTION_TARGET_UNREACHABLE
            value: "true"
        image: kuberhealthy/network-connection-check:v0.1.0
        name: kuberhealthy-metadata-unreachable

