build:
	docker build -t kuberhealthy/network-connection-check:v0.1.1 -f Dockerfile ../../
	# docker build -t jonnydawg/network-connection-check:v0.1.12 -f Dockerfile ../../

push:
	docker push kuberhealthy/network-connection-check:v0.1.1
	# docker push jonnydawg/network-connection-check:v0.1.12