apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: kuberhealthy-github-reachable
  namespace: kuberhealthy
spec:
  runInterval: 30m
  timeout: 125s
  podSpec:
    containers:
      - env:
          - name: CHECK_POD_TIMEOUT
            value: "10s"
          - name: CONNECTION_TARGET
            value: "tcp://github.com:443"
        image: kuberhealthy/network-connection-check:v0.1.0
        name: kuberhealthy-github-reachable

