apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: namespace-pod-check
  namespace: kuberhealthy
spec:
  runInterval: 1h
  timeout: 10m
  podSpec:
    serviceAccountName: namespace-pod-check
    containers:
      - name: namespace-pod-check
        image: kuberhealthy/namespace-pod-check:v1.1.1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 15m
            memory: 15Mi
          limits:
            cpu: 25m
    restartPolicy: Always
    terminationGracePeriodSeconds: 5
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-pod-check
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kuberhealthy
subjects:
  - kind: ServiceAccount
    name: namespace-pod-check
    namespace: kuberhealthy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: namespace-pod-check
  namespace: kuberhealthy
