apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: cronjob-checker
  namespace: kuberhealthy
spec:
  runInterval: 1h
  timeout: 10m
  podSpec:
    serviceAccountName: cronjob-checker
    containers:
      - name: cronjob-checker
        image: kuberhealthy/cronjob-checker:v1.1.0
        imagePullPolicy: IfNotPresent
        env:
          - name: NAMESPACE
            value: "kuberhealthy"
          - name: REASON
            value: "FailedNeedsStart"
        resources:
          requests:
            cpu: 15m
            memory: 15Mi
          limits:
            cpu: 25m
        restartPolicy: Always
    terminationGracePeriodSeconds: 5
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cronjob-checker
rules:
  - apiGroups:
      - ""
      - "events.k8s.io"
    resources:
      - events
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cronjob-checker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cronjob-checker
subjects:
  - kind: ServiceAccount
    name: cronjob-checker
    namespace: kuberhealthy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cronjob-checker
  namespace: kuberhealthy
