apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: kh-daemonset-external-check
  namespace: kuberhealthy
spec:
  runInterval: 30s
  timeout: 15m
  podSpec:
    containers:
      - env:
          - name: POD_NAMESPACE
            value: "kuberhealthy"
        image: docker-proto.repo.theplatform.com/kh-check-daemonset:1.0.0
        imagePullPolicy: IfNotPresent
        name: main
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
