apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: kh-daemonset-external-check
  namespace: default
spec:
  runInterval: 30s
  podSpec:
    containers:
      - env:
          - name: POD_NAMESPACE
            value: "default"
        image: daemonsetexternalcheck:latest
        imagePullPolicy: Never
        name: main
        resources:
          requests:
            cpu: 10m
            memory: 50Mi