apiVersion: comcast.github.io/v1
kind: KuberhealthyJob
metadata:
  name: daemonset-job2
  namespace: kuberhealthy
spec:
  # Make sure this Kuberhealthy check timeout is GREATER THAN the daemonset checker timeout
  # set in the env var CHECK_POD_TIMEOUT. Default is set to 5m (5 minutes).
  timeout: 3m
  podSpec:
    containers:
      - env:
          - name: POD_NAMESPACE
            value: "kuberhealthy"
        image: kuberhealthy/daemonset-check:v3.2.1
        imagePullPolicy: IfNotPresent
        name: main
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
    serviceAccountName: daemonset-khcheck

