apiVersion: comcast.github.io/v1
kind: KuberhealthyJob
metadata:
  name: http-job
  namespace: kuberhealthy
spec:
  timeout: 2m
  podSpec:
    containers:
      - name: http
        image: kuberhealthy/http-check:v1.3.1
        imagePullPolicy: IfNotPresent
        env:
          - name: CHECK_URL
            value: "http://google.com"
          - name: COUNT
            value: "1"
          - name: SECONDS
            value: "1"
          - name: PASSING_PERCENT
            value: "100"
        resources:
          requests:
            cpu: 15m
            memory: 15Mi
          limits:
            cpu: 25m
        restartPolicy: Always
    terminationGracePeriodSeconds: 5
