---
# Source: kuberhealthy/templates/khcheck-pod-restarts.yaml
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: pod-restarts
  namespace: kuberhealthy
spec:
  runInterval: 5m
  timeout: 10m
  podSpec:
    securityContext:
      runAsUser: 999
      fsGroup: 999
    containers:
      - env:
          - name: MAX_FAILURES_ALLOWED
            value: "10"
        image: kuberhealthy/pod-restarts-check:v2.5.1
        imagePullPolicy: IfNotPresent
        name: main
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
    restartPolicy: Never
    serviceAccountName: pod-restart-sa
---
# Source: kuberhealthy/templates/khcheck-pod-restarts.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-restart-sa
  namespace: kuberhealthy
---
# Source: kuberhealthy/templates/khcheck-pod-restarts.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-restart-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - list

---
# Source: kuberhealthy/templates/khcheck-pod-restarts.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-restart-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-restart-role
subjects:
  - kind: ServiceAccount
    name: pod-restart-sa
    namespace: kuberhealthy
