apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: pod-restarts
  namespace: kuberhealthy
spec:
  runInterval: 5m
  timeout: 10m
  podSpec:
    securityContext:
      runAsUser: 999
      fsGroup: 999
    containers:
      - env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MAX_FAILURES_ALLOWED
            value: "10"
        image: kuberhealthy/pod-restarts-check:v2.4.0
        imagePullPolicy: IfNotPresent
        name: main
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
    restartPolicy: Never
    serviceAccountName: pod-restart-sa
---
# Source: kuberhealthy/templates/khcheck-pod-restarts.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-restart-sa
  namespace: kuberhealthy
---
# Source: kuberhealthy/templates/khcheck-pod-restarts.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-restart-role
  namespace: kuberhealthy
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - list

---
# Source: kuberhealthy/templates/khcheck-pod-restarts.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-restart-rb
  namespace: kuberhealthy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-restart-role
subjects:
  - kind: ServiceAccount
    name: pod-restart-sa
