apiVersion: v1
entries:
  kuberhealthy:
  - apiVersion: v2
    appVersion: 2.2.0
    created: "2020-06-12T15:31:18.295498-07:00"
    description: An operator for synthetic test and monitoring.  Works great with
      Prometheus.
    digest: 0a57ed0ecc85ee985af3118ebb2cc586e41393f1333a8e4b189dcaddf0fb0a44
    home: https://comcast.github.io/kuberhealthy/
    icon: https://raw.githubusercontent.com/Comcast/kuberhealthy/master/images/logo-square.png
    keywords:
    - kuberhealthy
    - kubernetes
    - operator
    - monitoring
    - synthetic
    - testing
    - comcast
    - health
    - prometheus
    maintainers:
    - email: eric.greer@comcast.com
      name: integrii
    - email: jacob.martin@comcast.com
      name: lolimjake
    - email: ianhoegen@gmail.com
      name: ihoegen
    - email: jonathan_phan@comcast.com
      name: jonnydawg
    - email: joshulyne_park@comcast.com
      name: joshulyne
    name: kuberhealthy
    sources:
    - https://github.com/Comcast/kuberhealthy
    - https://github.com/helm/charts/tree/master/stable/kuberhealthy
    type: application
    urls:
    - kuberhealthy-2.2.0.tgz
    version: 2.2.0
generated: "2020-06-12T15:31:18.294274-07:00"
