---
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: kh-ami-check
  namespace: kuberhealthy
spec:
  runInterval: 10m
  timeout: 15m
  extraAnnotations:
    iam.amazonaws.com/role: <role-arn> # Replace this value with your ARN
  podSpec:
    containers:
    - name: kh-ami-check
      image: 
      imagePullPolicy: IfNotPresent
      env:
        - name: AWS_REGION
          value: "us-east-1"
        - name: AWS_S3_BUCKET_NAME
          value: "s3-bucket-name"
        - name: CLUSTER_FQDN
          value: "cluster.k8s"
      resources:
        requests:
          cpu: 10m
          memory: 10Mi
        limits:
          cpu: 15m
      restartPolicy: Always
