apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuberhealthy
  namespace: kuberhealthy
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kuberhealthy
            port:
              number: 80
