---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kuberhealthy.name" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
