apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-reaper
  namespace: kuberhealthy
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: check-reaper
              image: kuberhealthy/check-reaper:v1.2.1
              imagePullPolicy: IfNotPresent
#              env:
#                - name: SINGLE_NAMESPACE
#                  value: kuberhealthy
          restartPolicy: OnFailure
          serviceAccountName: check-reaper
  concurrencyPolicy: Forbid
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: check-reaper
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: check-reaper
    namespace: kuberhealthy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: check-reaper
  namespace: kuberhealthy
