apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-reaper
  namespace: kuberhealthy
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: kuberhealthy/check-reaper:v1.5.0
              imagePullPolicy: IfNotPresent
              name: check-reaper
              resources:
                requests:
                  cpu: 10m
                  memory: 50Mi
              env:
                - name: SINGLE_NAMESPACE
                  value: ""
                - name: MAX_PODS_THRESHOLD
                  value: "4"
                - name: JOB_DELETE_TIME_DURATION
                  value: 15m
          restartPolicy: OnFailure
          serviceAccountName: check-reaper
  concurrencyPolicy: Forbid
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuberhealthy-check-reaper
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
      - list
  - apiGroups:
      - comcast.github.io
    resources:
      - khjobs
    verbs:
      - delete
      - list
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: check-reaper
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kuberhealthy-check-reaper
subjects:
  - kind: ServiceAccount
    name: check-reaper
    namespace: kuberhealthy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: check-reaper
  namespace: kuberhealthy
