apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-reaper
  namespace: kuberhealthy
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: check-reaper
              image: kuberhealthy/check-reaper:v1.5.0
              imagePullPolicy: Always
              env:
                - name: SINGLE_NAMESPACE
                  value: kuberhealthy
                - name: MAX_PODS_THRESHOLD
                  value: "4"
                - name: JOB_DELETE_TIME_DURATION
                  value: 15m
          restartPolicy: OnFailure
          serviceAccountName: check-reaper
  concurrencyPolicy: Forbid
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: check-reaper
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kuberhealthy
subjects:
  - kind: ServiceAccount
    name: check-reaper
    namespace: kuberhealthy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: check-reaper
  namespace: kuberhealthy
