apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: image-download-check
  namespace: kuberhealthy
spec:
  runInterval: 10m
  timeout: 25m
  podSpec:
    containers:
      - name: image-download-check
        image: kuberhealthy/image-download-check:v0.1.0
        imagePullPolicy: IfNotPresent
        env:
          - name: FULL_IMAGE_URL
            value: "nginx:1.21"   #### example: docker pull nginx:1.21
          - name: TIMEOUT_LIMIT
            value: "180s"         #### in seconds
        resources:
          requests:
            cpu: 15m
            memory: 15Mi
          limits:
            cpu: 25m
    restartPolicy: Always
    terminationGracePeriodSeconds: 5
