build:
	docker build -t kuberhealthy/image-download-check:v0.0.1 -f Dockerfile ../../

buildmike:
	docker build -t mikeinton/image-download-check:v0.0.1 -f Dockerfile ../../

push:
	docker push kuberhealthy/image-download-check:v0.0.1

pushmike:
	docker push mikeinton/image-download-check:v0.0.1
