apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: http
  namespace: kuberhealthy
spec:
  runInterval: 5m
  timeout: 10m
  podSpec:
    containers:
      - name: https
        image: kuberhealthy/http-check:v1.4.1
        imagePullPolicy: IfNotPresent
        env:
          - name: CHECK_URL
            value: "https://reqres.in/api/users"
          - name: COUNT            #### default: "0"
            value: "5"
          - name: SECONDS          #### default: "0"
            value: "1"
          - name: PASSING_PERCENT  #### default: "100"
            value: "80"
          - name: REQUEST_TYPE     #### default: "GET"
            value: "POST"
          - name: REQUEST_BODY     #### default: "{}"
            value: '{"name": "morpheus", "job": "leader"}'
          - name: EXPECTED_STATUS_CODE #### default: "200"
            value: "201"
        resources:
          requests:
            cpu: 15m
            memory: 15Mi
          limits:
            cpu: 25m
        restartPolicy: Always
    terminationGracePeriodSeconds: 5
