// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/kuberhealthy/kuberhealthy/v2/pkg/apis/khjob/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKuberhealthyJobs implements KuberhealthyJobInterface
type FakeKuberhealthyJobs struct {
	Fake *FakeComcastV1
	ns   string
}

var kuberhealthyjobsResource = v1.SchemeGroupVersion.WithResource("kuberhealthyjobs")

var kuberhealthyjobsKind = v1.SchemeGroupVersion.WithKind("KuberhealthyJob")

// Get takes name of the kuberhealthyJob, and returns the corresponding kuberhealthyJob object, and an error if there is any.
func (c *FakeKuberhealthyJobs) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.KuberhealthyJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(kuberhealthyjobsResource, c.ns, name), &v1.KuberhealthyJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.KuberhealthyJob), err
}

// List takes label and field selectors, and returns the list of KuberhealthyJobs that match those selectors.
func (c *FakeKuberhealthyJobs) List(ctx context.Context, opts metav1.ListOptions) (result *v1.KuberhealthyJobList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(kuberhealthyjobsResource, kuberhealthyjobsKind, c.ns, opts), &v1.KuberhealthyJobList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.KuberhealthyJobList{ListMeta: obj.(*v1.KuberhealthyJobList).ListMeta}
	for _, item := range obj.(*v1.KuberhealthyJobList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kuberhealthyJobs.
func (c *FakeKuberhealthyJobs) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(kuberhealthyjobsResource, c.ns, opts))

}

// Create takes the representation of a kuberhealthyJob and creates it.  Returns the server's representation of the kuberhealthyJob, and an error, if there is any.
func (c *FakeKuberhealthyJobs) Create(ctx context.Context, kuberhealthyJob *v1.KuberhealthyJob, opts metav1.CreateOptions) (result *v1.KuberhealthyJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(kuberhealthyjobsResource, c.ns, kuberhealthyJob), &v1.KuberhealthyJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.KuberhealthyJob), err
}

// Update takes the representation of a kuberhealthyJob and updates it. Returns the server's representation of the kuberhealthyJob, and an error, if there is any.
func (c *FakeKuberhealthyJobs) Update(ctx context.Context, kuberhealthyJob *v1.KuberhealthyJob, opts metav1.UpdateOptions) (result *v1.KuberhealthyJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(kuberhealthyjobsResource, c.ns, kuberhealthyJob), &v1.KuberhealthyJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.KuberhealthyJob), err
}

// Delete takes name of the kuberhealthyJob and deletes it. Returns an error if one occurs.
func (c *FakeKuberhealthyJobs) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(kuberhealthyjobsResource, c.ns, name, opts), &v1.KuberhealthyJob{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKuberhealthyJobs) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(kuberhealthyjobsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.KuberhealthyJobList{})
	return err
}

// Patch applies the patch and returns the patched kuberhealthyJob.
func (c *FakeKuberhealthyJobs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.KuberhealthyJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(kuberhealthyjobsResource, c.ns, name, pt, data, subresources...), &v1.KuberhealthyJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.KuberhealthyJob), err
}
