name: Build and Push DNS-Resolution-Check Latest
on:
  push:
    branches:
    - master
    - release/*
    - docker-hub # for testing this build spec
    paths:
      - "cmd/dns-resolution-check/**"
env:
    IMAGE_NAME: dns-resolution-check
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: dockerfile sweep for best practices
      uses: burdzwastaken/hadolint-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HADOLINT_ACTION_DOCKERFILE_FOLDER: cmd/dns-resolution-check
        HADOLINT_ACTION_COMMENT: false
    - name: Log into docker hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u integrii --password-stdin
    - name: Push new latest image
      run: make -C cmd/dns-resolution-check push
    - name: scan docker image for vulnerabilities
      run: curl -s https://ci-tools.anchore.io/inline_scan-v0.6.0 | bash -s -- -p -r kuberhealthy/$IMAGE_NAME:latest
