name: Build and Push Check-Reaper Latest
on:
  push:
    branches:
    - master
    - release/*
    - docker-hub # for testing this build spec
    paths:
      - "cmd/check-reaper/**"
env:
    IMAGE_NAME: check-reaper
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build container
      run: docker build --file cmd/check-reaper/Dockerfile --tag $IMAGE_NAME .
    - name: Log into docker hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u integrii --password-stdin
    - name: Push new latest image
      run: |
          docker tag $IMAGE_NAME kuberhealthy/$IMAGE_NAME
          docker push kuberhealthy/$IMAGE_NAME
