name: Build Flat Spec Files from Helm Chart
on:
  push:
    paths:
      - 'deploy/helm/*'
    branches:
      - master
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
    - name: Build Helm Chart
      uses: stefanprodan/kube-tools@v1.3.0
      with:
        working-directory: deploy/
        command: ./create-flat-files.sh
        #kubectl: # optional
        # kustomize version e.g. 3.5.4
        #kustomize: # optional
        # helm version e.g. 2.16.1
        #helm: # optional
        # helm version e.g. 3.0.2
        #helmv3: # optional
  commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Automatic Template Render Job"
        git commit -m "re-render flat spec files" -a
    - name: "push changes back to repository"
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
