name: Build Flat Spec Files from Helm Chart
on:
  push:
#    paths:
#      - 'deploy/helm/kuberhealthy/*'
#    branches:
#      - master
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
    - name: Build Helm Chart
      uses: stefanprodan/kube-tools@v1.3.0
      with:
        working-directory: deploy/helm/
        command: pwd; ;ls -al
        #kubectl: # optional
        # kustomize version e.g. 3.5.4
        #kustomize: # optional
        # helm version e.g. 2.16.1
        #helm: # optional
        # helm version e.g. 3.0.2
        #helmv3: # optional
    - name: Build Helm Chart
      uses: stefanprodan/kube-tools@v1.3.0
      with:
        working-directory: deploy/helm/
        command: ./deploy/helm/create-flat-files.sh
        #kubectl: # optional
        # kustomize version e.g. 3.5.4
        #kustomize: # optional
        # helm version e.g. 2.16.1
        #helm: # optional
        # helm version e.g. 3.0.2
        #helmv3: # optional
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2.4.4
      with:
        # GITHUB_TOKEN or a repo scoped PAT
        token: ${{ secrets.GITHUB_TOKEN }}
        # Relative path under $GITHUB_WORKSPACE to the repository.
        #path: # optional
        # The message to use when committing changes.
        commit-message: "flat file spec regeneration"
        # The committer name and email address.
        author: "action@github.com"
        # The author name and email address.
        committer: "GitHub Automatic Template Render Job"
        # The title of the pull request.
        title: "Flat Spec File Regeneration"
        # The body of the pull request.
        body: "An automatic PR for the regeneration of flat deployment files."
        # A comma separated list of labels.
        #labels: # optional
        # A comma separated list of assignees (GitHub usernames).
        #assignees: # optional
        # A comma separated list of reviewers (GitHub usernames) to request a review from.
        #reviewers: # optional
        # A comma separated list of GitHub teams to request a review from.
        #team-reviewers: # optional
        # The number of the milestone to associate this pull request with.
        #milestone: # optional
        # The name of the project for which a card should be created.
        #project: # optional
        # The name of the project column under which a card should be created.
        #project-column: # optional
        # The pull request branch name.
        branch: flat-file-auto-regen
        # The pull request base branch.
        base: master
        # The branch suffix type.
        #branch-suffix: # optional
