name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: ':wave: Welcome to Kuberhealthy.  Thanks for opening your first issue.'
        pr-message: 'Thanks for your pull request!  Welcome to the community. :thumbsup:'
