apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: ssl-handshake
  namespace: kuberhealthy
spec:
  runInterval: 5m
  timeout: 10m
  podSpec:
    containers:
      - env:
          # Domain name env variable must be updated to the domain on which you wish to check the SSL for
          - name: DOMAIN_NAME
            value: "kubernetes.default"
          # If not using default SSL port of 443, port env variable must be updated  
          - name: PORT
            value: "443"
          # For internal, self-signed certs, set to "true" and the handshake check will attempt to automatically retrieve the host certificate
          - name: SELF_SIGNED
            value: "true"
        image: kuberhealthy/ssl-handshake-check:v3.0.1
        imagePullPolicy: IfNotPresent
        name: main
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
